import { MarketMetric } from '../types/ticker';

export const INSTITUTIONAL_MARKET_METRICS: MarketMetric[] = [
  // 1. Forex & Spot Commodities
  {
    id: 'usd-zar',
    category: 'forex',
    symbol: 'USD / ZAR',
    name: 'US Dollar to South African Rand',
    value: 16.27,
    displayValue: 'R 16.27',
    unit: 'ZAR',
    change: '-0.14%',
    changeDirection: 'down',
    changePeriod: '24h',
    badge: 'FOREX SPOT',
    source: 'SARB / Global Interbank FX',
    sourceUrl: 'https://www.resbank.co.za',
    lastUpdated: 'Live Market Feed',
    underwritingNotes: 'Essential for imported capital equipment (HVAC, lifts, solar PV inverters, structural steel pricing).',
    historicalContext: 'Strengthened from R18.10 levels following inflation moderation and improved fiscal terms.',
    isLive: true,
  },
  {
    id: 'zar-usd',
    category: 'forex',
    symbol: 'ZAR / USD',
    name: 'South African Rand to US Dollar',
    value: 0.0615,
    displayValue: '$ 0.0615',
    unit: 'USD',
    change: '+0.14%',
    changeDirection: 'up',
    changePeriod: '24h',
    badge: 'FOREX SPOT',
    source: 'SARB / Global Interbank FX',
    sourceUrl: 'https://www.resbank.co.za',
    lastUpdated: 'Live Market Feed',
    underwritingNotes: 'Benchmark for foreign direct property investment and institutional offshore yields.',
    historicalContext: 'Inverted USD/ZAR parity.',
    isLive: true,
  },
  {
    id: 'gold-spot',
    category: 'forex',
    symbol: 'GOLD (XAU)',
    name: 'Spot Gold per Ounce',
    value: 4380.00,
    displayValue: '$ 4,380.00',
    unit: 'USD/oz',
    change: '+0.42%',
    changeDirection: 'up',
    changePeriod: '24h',
    badge: 'COMMODITY',
    source: 'LBMA / Kitco Spot',
    sourceUrl: 'https://www.kitco.com',
    lastUpdated: 'Live Spot Feed',
    underwritingNotes: 'Macro risk hedge indicator influencing safe-haven asset allocation and domestic mining revenue flows.',
    historicalContext: 'Trading in the $4,370 - $4,395/oz corridor amid heightened global central bank diversification.',
    isLive: true,
  },
  {
    id: 'gold-zar-g',
    category: 'forex',
    symbol: 'GOLD / ZAR (g)',
    name: 'Domestic Gold Price per Gram',
    value: 2285.00,
    displayValue: 'R 2,285.00',
    unit: 'ZAR/g',
    change: '+0.28%',
    changeDirection: 'up',
    changePeriod: '24h',
    badge: 'COMMODITY',
    source: 'JSE Commodities / LBMA Conversion',
    sourceUrl: 'https://www.jse.co.za',
    lastUpdated: 'Live Spot Feed',
    underwritingNotes: 'Local gold parity calculation ($/oz converted at USD/ZAR spot rate).',
    isLive: true,
  },
  {
    id: 'brent-crude',
    category: 'forex',
    symbol: 'BRENT CRUDE',
    name: 'Brent Crude Oil Spot',
    value: 103.87,
    displayValue: '$ 103.87',
    unit: 'USD/bbl',
    change: '-0.35%',
    changeDirection: 'down',
    changePeriod: '24h',
    badge: 'COMMODITY',
    source: 'ICE Futures / Global Energy Index',
    lastUpdated: 'Live Spot Feed',
    underwritingNotes: 'Direct driver of South African basic fuel price (BFP), logistics, bitumen, and material delivery surcharges.',
    historicalContext: 'Crude hovering near $103/bbl driven by global supply adjustments and shipping route dynamics.',
    isLive: true,
  },

  // 2. SARB Monetary Policy & South African Macro
  {
    id: 'sarb-repo-rate',
    category: 'macro',
    symbol: 'SARB REPO',
    name: 'SARB Monetary Policy Benchmark Rate',
    value: 7.00,
    displayValue: '7.00%',
    unit: 'p.a.',
    change: 'Held (7.00%)',
    changeDirection: 'neutral',
    changePeriod: 'MPC Benchmark',
    badge: 'POLICY RATE',
    source: 'South African Reserve Bank (SARB)',
    sourceUrl: 'https://www.resbank.co.za',
    lastUpdated: 'Official MPC Notice',
    underwritingNotes: 'Critical baseline for cost of capital, debt service coverage ratio (DSCR), and capitalization rates.',
    historicalContext: 'Set at 7.00% following targeted adjustments to maintain inflation within the SARB 3-6% band.',
    isLive: false,
  },
  {
    id: 'prime-lending-rate',
    category: 'macro',
    symbol: 'PRIME RATE',
    name: 'Commercial Bank Prime Lending Rate',
    value: 10.50,
    displayValue: '10.50%',
    unit: 'p.a.',
    change: 'Repo + 3.50%',
    changeDirection: 'neutral',
    changePeriod: 'Active Rate',
    badge: 'DEBT BENCHMARK',
    source: 'South African Reserve Bank / Commercial Banks',
    sourceUrl: 'https://www.resbank.co.za',
    lastUpdated: 'Active Benchmark',
    underwritingNotes: 'Base variable interest rate utilized in commercial property senior development loans (typically Prime + 0.5% to 2.0%).',
    historicalContext: 'Directly linked to SARB Repo rate (+350 bps spread).',
    isLive: false,
  },
  {
    id: 'cpi-inflation',
    category: 'macro',
    symbol: 'SA CPI',
    name: 'Headline Consumer Price Index Inflation',
    value: 4.3,
    displayValue: '4.3% YoY',
    unit: 'Annual',
    change: '-0.2% MoM',
    changeDirection: 'down',
    changePeriod: 'Stats SA Release',
    badge: 'INFLATION',
    source: 'Statistics South Africa (Stats SA)',
    sourceUrl: 'https://www.statssa.gov.za',
    lastUpdated: 'Latest Stats SA Release',
    underwritingNotes: 'Directly impacts municipal tariff escalations, annual lease escalation clauses (typically CPI + 1.5% to 2.5%), and tenant affordability.',
    historicalContext: 'Firmly anchored within the SARB target midpoint band (3% - 6%).',
    isLive: false,
  },
  {
    id: 'fuel-petrol-coastal',
    category: 'macro',
    symbol: 'PETROL 95 (COASTAL)',
    name: 'Unleaded Petrol 95 (Coastal Regulated)',
    value: 26.05,
    displayValue: 'R 26.05 / L',
    unit: 'ZAR/L',
    change: 'Inland: R26.92/L',
    changeDirection: 'neutral',
    changePeriod: 'DMRE Gazetted',
    badge: 'ENERGY / LOGISTICS',
    source: 'Department of Mineral Resources and Energy (DMRE)',
    sourceUrl: 'https://www.energy.gov.za',
    lastUpdated: 'Gazetted Price',
    underwritingNotes: 'Key input for site operations, civil plant diesel/petrol consumption, and employee transport indexing.',
    isLive: false,
  },
  {
    id: 'fuel-diesel-coastal',
    category: 'macro',
    symbol: 'DIESEL 50PPM (COASTAL)',
    name: 'Diesel 50ppm Wholesale (Coastal)',
    value: 29.18,
    displayValue: 'R 29.18 / L',
    unit: 'ZAR/L',
    change: 'Inland: R30.05/L',
    changeDirection: 'neutral',
    changePeriod: 'DMRE Gazetted',
    badge: 'ENERGY / LOGISTICS',
    source: 'Department of Mineral Resources and Energy (DMRE)',
    sourceUrl: 'https://www.energy.gov.za',
    lastUpdated: 'Gazetted Wholesale',
    underwritingNotes: 'Impacts bulk earthworks, site generators, aggregate trucking, and heavy equipment transport.',
    isLive: false,
  },

  // 3. Construction & Building Intelligence
  {
    id: 'afrimat-construction-index',
    category: 'construction',
    symbol: 'AFRIMAT ACI',
    name: 'Afrimat Construction Index',
    value: 132.8,
    displayValue: '132.8 pts',
    unit: 'Index Pts',
    change: '+0.3% YoY',
    changeDirection: 'up',
    changePeriod: 'Q1 Trend',
    badge: 'CONSTRUCTION INDEX',
    source: 'Afrimat / Dr. Roelof Botha',
    sourceUrl: 'https://www.afrimat.co.za',
    lastUpdated: 'Quarterly Release',
    underwritingNotes: 'Composite index tracking building materials volume, employment, architectural plans passed, and construction activity.',
    historicalContext: 'Three consecutive quarters of seasonally adjusted positive momentum across material sales and buildings completed.',
    isLive: false,
  },
  {
    id: 'wc-building-cost-standard',
    category: 'construction',
    symbol: 'WC BUILD COST (STD)',
    name: 'WC Standard Residential Construction Cost',
    value: 14500,
    displayValue: 'R 12k – R 18k / m²',
    unit: 'ZAR/m²',
    change: '+5.4% YoY',
    changeDirection: 'up',
    changePeriod: 'BER / QS Survey',
    badge: 'QS BENCHMARK',
    source: 'BER / SACPVP Quantity Surveying Benchmarks',
    lastUpdated: 'Active Valuation Table',
    underwritingNotes: 'Standard residential specification excluding professional fees, land cost, and bulk infrastructure contributions.',
    historicalContext: 'Reflects coastal material premiums and NHBRC compliance requirements in the Western Cape.',
    isLive: false,
  },
  {
    id: 'wc-building-cost-luxury',
    category: 'construction',
    symbol: 'WC BUILD COST (LUX)',
    name: 'WC High-End / Luxury Residential Build Cost',
    value: 22500,
    displayValue: 'R 18k – R 25k+ / m²',
    unit: 'ZAR/m²',
    change: '+6.8% YoY',
    changeDirection: 'up',
    changePeriod: 'Atlantic / Winelands',
    badge: 'LUXURY BENCHMARK',
    source: 'Western Cape Property Valuers & BER',
    lastUpdated: 'Active Valuation Table',
    underwritingNotes: 'Applicable to Atlantic Seaboard, Bishopscourt, Constantia, and Cape Winelands luxury residential developments.',
    historicalContext: 'Premium driven by bespoke engineering, heritage compliance, and luxury imported fittings.',
    isLive: false,
  },

  // 4. Western Cape Property Market Analytics
  {
    id: 'wc-house-price-inflation',
    category: 'property',
    symbol: 'WC HOUSE INFLATION',
    name: 'Western Cape House Price Annual Growth',
    value: 7.8,
    displayValue: '+7.8% YoY',
    unit: 'Annual Growth',
    change: 'Top SA Province',
    changeDirection: 'up',
    changePeriod: 'FNB / Lightstone',
    badge: 'PROPERTY INFLATION',
    source: 'FNB Property Barometer & Lightstone Data',
    sourceUrl: 'https://www.fnb.co.za',
    lastUpdated: 'Latest Regional Barometer',
    underwritingNotes: 'Consistently outperforming Gauteng and KZN by 300–450 bps, driven by ongoing semigration and lifestyle demand.',
    historicalContext: 'Growth extending across the City of Cape Town, Winelands, Overberg, and Garden Route corridors.',
    isLive: false,
  },
  {
    id: 'cpt-median-residential',
    category: 'property',
    symbol: 'CPT MEDIAN RES',
    name: 'Cape Town Metro Median House Price',
    value: 2150000,
    displayValue: 'R 2.15 Million',
    unit: 'ZAR Median',
    change: '+6.4% YoY',
    changeDirection: 'up',
    changePeriod: 'Metro Average',
    badge: 'MEDIAN VALUATION',
    source: 'Lightstone / FNB Metro Analytics',
    lastUpdated: 'Metro Registry',
    underwritingNotes: 'Baseline residential valuation benchmark for middle-market sectional title and freehold housing.',
    isLive: false,
  },
  {
    id: 'wc-rental-yield',
    category: 'property',
    symbol: 'WC RENTAL YIELD',
    name: 'Western Cape Sectional Title Gross Yield',
    value: 8.2,
    displayValue: '7.8% – 8.9%',
    unit: 'Gross Yield',
    change: '+0.5% YoY',
    changeDirection: 'up',
    changePeriod: 'PayProp / TPN',
    badge: 'YIELD BENCHMARK',
    source: 'PayProp Rental Index / TPN Credit Bureau',
    lastUpdated: 'Quarterly Yield Matrix',
    underwritingNotes: 'Western Cape tenants demonstrate the highest national good-standing credit rating (>86%).',
    isLive: false,
  },
  {
    id: 'wc-days-on-market',
    category: 'property',
    symbol: 'DAYS ON MARKET',
    name: 'Average Time on Market (Cape Town Metro)',
    value: 41,
    displayValue: '41 Days',
    unit: 'Days',
    change: '-37 Days vs SA Avg (78d)',
    changeDirection: 'down',
    changePeriod: 'Liquidity Index',
    badge: 'LIQUIDITY',
    source: 'FNB Estate Agent Survey',
    lastUpdated: 'Survey Benchmark',
    underwritingNotes: 'Indicates high transactional velocity and constrained stock availability in the Western Cape.',
    isLive: false,
  },

  // 5. Top Performing Western Cape Municipalities
  {
    id: 'muni-drakenstein',
    category: 'municipal',
    symbol: 'DRAKENSTEIN MUNI',
    name: 'Drakenstein Municipality (Paarl / Wellington)',
    value: 84,
    displayValue: '84 / 100',
    unit: 'Sustainability Score',
    change: '#1 SA Municipality',
    changeDirection: 'up',
    changePeriod: 'Ratings Afrika Index',
    badge: 'MUNICIPAL AUDIT',
    source: 'Ratings Afrika Municipal Financial Sustainability Index (MFSI)',
    lastUpdated: 'Official MFSI Report',
    underwritingNotes: 'Highest financial sustainability score in South Africa; clean AG audit, excellent infrastructure asset maintenance.',
    isLive: false,
  },
  {
    id: 'muni-saldanha-bay',
    category: 'municipal',
    symbol: 'SALDANHA BAY',
    name: 'Saldanha Bay Municipality (West Coast)',
    value: 82,
    displayValue: '82 / 100',
    unit: 'MFSI Score',
    change: '#2 in Western Cape',
    changeDirection: 'up',
    changePeriod: 'Ratings Afrika',
    badge: 'GROWTH HUB',
    source: 'Ratings Afrika MFSI / Industrial Development Zone (SBIDZ)',
    lastUpdated: 'Official MFSI Report',
    underwritingNotes: 'Strategic deep-water port hub, expanding green hydrogen and industrial logistics corridors.',
    isLive: false,
  },
  {
    id: 'muni-cape-town',
    category: 'municipal',
    symbol: 'CITY OF CAPE TOWN',
    name: 'City of Cape Town Metropolitan Municipality',
    value: 80,
    displayValue: '80 / 100',
    unit: 'MFSI Score',
    change: 'R120bn+ Infra Budget',
    changeDirection: 'up',
    changePeriod: '5-Year Capital Budget',
    badge: 'METRO LEADER',
    source: 'City of Cape Town / Auditor-General SA',
    sourceUrl: 'https://www.capetown.gov.za',
    lastUpdated: 'Annual Report / MFMA',
    underwritingNotes: 'Largest capital expenditure budget in SA dedicated to water/sanitation (Potsdam WWTW upgrade) and transport.',
    isLive: false,
  },
  {
    id: 'muni-overstrand',
    category: 'municipal',
    symbol: 'OVERSTRAND MUNI',
    name: 'Overstrand Municipality (Hermanus / Gansbaai)',
    value: 79,
    displayValue: '79 / 100',
    unit: 'MFSI Score',
    change: 'High Governance',
    changeDirection: 'up',
    changePeriod: 'Ratings Afrika',
    badge: 'LIFESTYLE CORRIDOR',
    source: 'Ratings Afrika MFSI',
    lastUpdated: 'MFSI Index',
    underwritingNotes: 'Strong debt coverage ratio, tourism-driven development and high rates collection rate (>96%).',
    isLive: false,
  },
  {
    id: 'muni-stellenbosch',
    category: 'municipal',
    symbol: 'STELLENBOSCH MUNI',
    name: 'Stellenbosch Municipality (Cape Winelands)',
    value: 78,
    displayValue: '78 / 100',
    unit: 'MFSI Score',
    change: 'Innovation Hub',
    changeDirection: 'up',
    changePeriod: 'Ratings Afrika',
    badge: 'WINELANDS',
    source: 'Ratings Afrika MFSI / AGSA',
    lastUpdated: 'MFSI Index',
    underwritingNotes: 'High-income municipal tax base, robust town planning approvals, leading commercial IPP solar adoption.',
    isLive: false,
  },

  // 6. Western Cape Grid & Eskom Power Reliability
  {
    id: 'eskom-wc-eaf',
    category: 'energy',
    symbol: 'WC ESKOM EAF',
    name: 'Energy Availability Factor (Western Cape Grid)',
    value: 64.2,
    displayValue: '64.2% EAF',
    unit: 'Generation Capacity',
    change: '+4.1% YoY',
    changeDirection: 'up',
    changePeriod: 'Eskom System Status',
    badge: 'GRID AVAILABILITY',
    source: 'Eskom National System Operator',
    sourceUrl: 'https://www.eskom.co.za',
    lastUpdated: 'Eskom Adequacy Report',
    underwritingNotes: 'Supported by Koeberg Nuclear Power Station (1,860 MW) baseload output and Ankerlig OCGT reserve.',
    isLive: false,
  },
  {
    id: 'cpt-steenbras-shielding',
    category: 'energy',
    symbol: 'STEENBRAS HYDRO',
    name: 'City of Cape Town Pumped Storage Scheme',
    value: 180,
    displayValue: 'Up to 2 Stages Protection',
    unit: '180 MW Capacity',
    change: 'Active Protection',
    changeDirection: 'up',
    changePeriod: 'Municipal Grid',
    badge: 'GRID RESILIENCE',
    source: 'City of Cape Town Energy Directorate',
    sourceUrl: 'https://www.capetown.gov.za',
    lastUpdated: 'Operational Feed',
    underwritingNotes: 'Shields Cape Town residential and industrial customers from national load-shedding stages (180 MW pumped storage).',
    historicalContext: 'Enables higher productivity and lower commercial backup diesel generation costs for Western Cape developments.',
    isLive: true,
  },
  {
    id: 'cpt-industrial-uptime',
    category: 'energy',
    symbol: 'COCT GRID RELIABILITY',
    name: 'Industrial Zone Grid Reliability & Uptime',
    value: 99.1,
    displayValue: '99.1% Uptime',
    unit: 'Network Uptime',
    change: 'Leading SA Metro',
    changeDirection: 'up',
    changePeriod: 'City Power Grid',
    badge: 'INFRASTRUCTURE',
    source: 'City of Cape Town Energy & Climate Change Directorate',
    lastUpdated: 'Annual Reliability Survey',
    underwritingNotes: 'Key underwriting metric for cold storage, data centres, manufacturing, and mixed-use commercial projects.',
    isLive: false,
  },
];
